# Generated by Django 3.0.3 on 2020-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=20)),
                ('book_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(max_length=50)),
                ('message', models.TextField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
